//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestWeb_client.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IBuildingSearch")]
    public interface IBuildingSearch {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBuildingSearch/getBuildings", ReplyAction="http://tempuri.org/IBuildingSearch/getBuildingsResponse")]
        string[] getBuildings(string userInput);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBuildingSearch/getBuildings", ReplyAction="http://tempuri.org/IBuildingSearch/getBuildingsResponse")]
        System.Threading.Tasks.Task<string[]> getBuildingsAsync(string userInput);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IBuildingSearchChannel : TestWeb_client.ServiceReference1.IBuildingSearch, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class BuildingSearchClient : System.ServiceModel.ClientBase<TestWeb_client.ServiceReference1.IBuildingSearch>, TestWeb_client.ServiceReference1.IBuildingSearch {
        
        public BuildingSearchClient() {
        }
        
        public BuildingSearchClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public BuildingSearchClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BuildingSearchClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BuildingSearchClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string[] getBuildings(string userInput) {
            return base.Channel.getBuildings(userInput);
        }
        
        public System.Threading.Tasks.Task<string[]> getBuildingsAsync(string userInput) {
            return base.Channel.getBuildingsAsync(userInput);
        }
    }
}
